// <auto-generated />
using DISCREESTR.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DISCREESTR.Infrastructure.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DISCREESTR.DOMAIN.Prep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Otcestvo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Preps");
                });

            modelBuilder.Entity("DISCREESTR.DOMAIN.Studplan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Clocks")
                        .HasColumnType("int");

                    b.Property<string>("FormControl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KursNumb")
                        .HasColumnType("int");

                    b.Property<string>("PredmName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrepId")
                        .HasColumnType("int");

                    b.Property<int>("Semestr")
                        .HasColumnType("int");

                    b.Property<string>("Specname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PrepId");

                    b.ToTable("Studplans");
                });

            modelBuilder.Entity("DISCREESTR.DOMAIN.Studplan", b =>
                {
                    b.HasOne("DISCREESTR.DOMAIN.Prep", "Prep")
                        .WithMany("Studplans")
                        .HasForeignKey("PrepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prep");
                });

            modelBuilder.Entity("DISCREESTR.DOMAIN.Prep", b =>
                {
                    b.Navigation("Studplans");
                });
#pragma warning restore 612, 618
        }
    }
}
